### ISSUE TITLE
Issues #1

### ISSUE THREAD

**Issue by OhBall** [ricksyuan/heap-overflow#3]
- [x] Form-submission causes a 500 level internal server error (check your server logs using `heroku logs` in the command line). If I had to guess, it may be a migration issue.

- [x] Demo login does not work.

- [x] Footer does not sit at the bottom of the page.

**Comment by ricksyuan** [comment]
Thanks for the feedback! It was indeed a migration issue. I had not run the database migrations and seeding on Heroku. I have done so and I believe that has fixed the issues with logging in. You should now be able to use the demo login. I have also addressed  the footer issue by adding a min-height constraint to the main content section. Thanks for your help and please let me know if you encounter any further issues with the auth!
