### ISSUE TITLE
1/31 Issues

### ISSUE THREAD

**Issue by OhBall** [ricksyuan/heap-overflow#4]
- [x] When navigating back to the front page from a questions show page, there is no 

- [x] On the ask a question form, it perpetually displays `Loading...` above the form.

- [x] The discard button of the question form does not work.

- [x] When clicking on a question's title on the question show page, it redirects you to `/questions/undefined`

**Comment by ricksyuan** [comment]
All fixed! Thanks for the help and feedback!
